mqtt:
  username: admin
  password: public
  host-url:
    - tcp://localhost:1883
  client-id: mqttId2
  mail-topic: mail
  comment-topic: comment
  connection-timeout: 3000
  mail-subscription-topic:
    - /mail/id/+/publish
  comment-subscription-topic:
    - /comment/id/+/publish/
    