server:
  port: 8383
  
mqtt:
  username: admin
  password: public
  host-url:
    - tcp://localhost:1883
  client-id: ${COMPUTERNAME}-${server.port}
  mail-topic: mail
  comment-topic: comment
  connection-timeout: 3000
  mail-subscription-topic:
    - $share/mailGroup/mailFilter/mailId/+/topic
   
  comment-subscription-topic:
    - $share/commentGroup/commentFilter/commentId/+/topic
    
